
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zk?useSSL=false&useUnicode=true&characterEncoding=utf-8
    password: qdbQDB246
    username: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
server:
  port: 8088